### ISSUE TITLE
Trouble Printing Out Information Gathered From LinkedIn API

### ISSUE THREAD

**Issue by ambethoney** [ambethoney/linkedin_oauth#1]
Hi PJ,

I'm getting some errors whenever I try to create a list of contacts obtained from the LinkedIn API. The error I'm currently receiving is 
/
# <NoMethodError: undefined method `lrange' for nil:NilClass>

/

I understand what this error means, I'm just having a hard time trying to figure out how to get the contacts to print out! I've tried using an lrange method and an each do method, but I keep receiving a nil error. I'm not sure why my code is unable to retrieve this information. Help!

**Comment by ambethoney** [comment]
Hey PJ,
Just following up on this issue. I'm wondering if you have time to meet with me, or should I ask one of the other teachers if they have time.

**Comment by ghost** [comment]
I'll look at it right now.

**Comment by ghost** [comment]
Can you send me, over hipchat, your LI environmental vars? (not here!)

**Comment by ghost** [comment]
So, this is the error you're getting?

```
#<NoMethodError: undefined method `lrange' for nil:NilClass>
```

**Comment by ambethoney** [comment]
At this point, I’m receiving an undefined variable “id”. I’ve pushed up my changes so you can take a look.

What I’m trying to do is print out a list of contacts. I would like for those contacts to be links to a profile page for each contact. I’m thinking I would need to assign each contact and id number in order to give each their own profile. I’m still stuck.

**Comment by ghost** [comment]
ah ok, let me pull and i'll check.

**Comment by ghost** [comment]
your indentation is a mess. next time, i'll just ask you to fix it before working on the issue.

**Comment by ambethoney** [comment]
sorry :(

**Comment by ghost** [comment]
Ok fixed problem -- sending you a PR
